version: 2

sources:
  - name: subscribers
    tables:
      - name: active_users
      - name: cases
      - name: dim_customer
      - name: dim_geo
      - name: dim_product
      - name: product

models:
  - name: fact_cases
    description: One record per case contacting customer service
    columns:
      - name: case_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: Datetime
        description: Date of case occurence.
      - name: Customer_id
        description: Unique customer identifier
        test:
          - not_null
      - name: Channel
        description: Method of contact
        tests:
          - accepted_values:
              values: ['email', 'phone']
      - name: Reason
        description: Reason for contact with customer services 
        tests:
          - accepted_values:
              values: ['support', 'signup']
  
  - name: dim_customer
    description: One record per customer with general info
    columns:
      - name: Customer_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: Age
        description: Customer age as integer
      - name: Gender
        description: Gender
        test:
        - accepted_values:
              values: ['female', 'male']
      - name: Age_group
        description: 10-year age brackets
      - name: Geo_id
        description: Unique municipality identifier
  
  - name: dim_geo
    description: One record per municipality
    columns:
      - name: Geo_id
        description: Primary key
        tests:
          - unique
          - not_null 
      - name: Kommune
        description: Municipality
      - name: Region
        description: Region
  
  - name: dim_product
    description: One record per product sold
    columns:
      - name: Product_id
        description: Primary key
        tests:
          - unique
          - not_null 
      - name: Name
        description: Product name
      - name: Price
        description: Product price
      - name: Billing_cycle
        description: Billing cycle for product
  
  - name: fact_product
    description: One record per customer
    columns:
      - name: Customer_id
        description: Primary key
        tests:
          - unique
          - not_null 
      - name: Signup_date_time
        description: Date of signing up
      - name: Cancel_date_time
        description: Date of cancelation. OBS! if it is year 2100 customer is currently active

  - name: fact_active
    description: One record per customer
    columns:
      - name: Customer_id
        description: Primary key
        tests:
          - unique
          - not_null 
      - name: Active
        description: Is the customer active on this date (true=1)
      - name: New_customer
        description: Is the customer new this month (true=1)
      - name: Cancel
        description: Did the customer cancel this month (true=1)